Members Only project completed
angel-mora/members_only pull request #2
Opened 2020-10-01 20:47 UTC by angel-mora

## Additional features were added, such as:

- Permission to edit only available if current user is author of post
- Created models, controllers and views properly with scaffolding methods
- Devise gem for authentication properly implemented
- Herb gem used to preview datasets in rails console
- Linters issues addressed

2020-10-02 01:33 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @angel-mora and @gabrie-lhilarion :balloon: :lollipop: 

### Thank you for your submission :handshake: :handshake: your project looks great and it's working well :ok_hand: I like that you've implemented all the actions for the Post entity not only for creating and showing but also updating and deleting claps to you for that :clap: :clap: :clap: with that said, there are some changes left to make so let's get to them :construction: :construction_worker: :construction_worker: 

#### Behavior

- [ ] User's shouldn't be able to edit or destroying posts that aren't their own

> these actions (updating and deleting posts) weren't requested so if you want to keep them let's add a before filter in your controller that prevents users from editing and/or deleting posts that aren't their own.

#### No Logic or complexity in views or partials

* [ ] There should be absolutely NO logic or complexity (if, if/else, unless or ternary operators) in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources** [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)

- I've left comments directly in your code with suggestions on how to handle the complexity I've found in your views

### That's it, team! :raised_hands:  

### Please :pray: do the changes :technologist: :technologist: and submit  back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-10-02 01:33 UTC, euqueme commented on app/views/layouts/application.html.erb
> +    <% end %>
- [ ] Put the if/else statement in a helper method and call the helper method here instead of having the if/else statement directly in this view

2020-10-02 01:33 UTC, euqueme commented on app/views/posts/_form.html.erb
> +  <% end %>
- [ ] Put the if statement in a helper method and use a partial to put the contents of the if statement so you can render the partial within the if statement and call the helper method here instead of having the if statement directly in this view

2020-10-02 01:33 UTC, euqueme commented on app/views/posts/index.html.erb
> +            <% end %>
- [ ] Put the if statement in a helper method and call the helper method here instead of having the if statement directly in this view

2020-10-02 01:33 UTC, euqueme commented on app/views/posts/index.html.erb
> +            <% end %>
- [ ] Put the if statement in a helper method and call the helper method here instead of having the if statement directly in this view

2020-10-07 17:35 UTC, angel-mora commented
# Changes addressed

- Removed logic from views
- Just authors of posts can erase them

2020-10-07 18:02 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for making the suggested changes, You can merge it now :+1: 

Good continuation :handshake: 

Thanks.
Mael FOSSO

2020-10-07 20:00 UTC, merged